import { join, resolve } from "node:path";
import { prepareRun, redactSecrets } from "./lib/core.mjs";
import { executeRun, resumeRun } from "./lib/orchestrator.mjs";
import { startPreview } from "./lib/preview.mjs";
import { runElevation3d } from "./lib/unified-flow.mjs";
import { facadeAgentToolSchema, runFacadeAgentTool } from "./lib/facade-agent/cli.mjs";
import { facadeDesignAgentToolSchema, runFacadeDesignAgentTool } from "./lib/facade-agent/design/index.mjs";

const briefSchema = { type: "object", properties: { summary_ko: { type: "string" }, materials: { type: "array", items: { type: "string" } }, window_rhythm: { type: "string" }, ground_floor: { type: "string" }, roof: { type: "string" }, negative_constraints: { type: "array", items: { type: "string" } } }, required: ["summary_ko", "materials", "window_rhythm", "ground_floor", "roof", "negative_constraints"] };

export async function register(api) {
	const datasetRoot = api.config.dataset_root ?? "D:/Data/50_ELE/MAAS_ELEVATION_TEST_SET_20260730";
	const outputRoot = resolve(api.config.output_root ?? "results");
	const facadeFetch = typeof api.fetch === "function" ? api.fetch : globalThis.fetch?.bind(globalThis);
	api.addPrompt("For a complete candidate package, prefer elevation_3d_run. An accepted enriched run automatically produces and browser-verifies one selected GLB plus front, back, left, right, plan, top, axon, and opposite-axon views. Exact-MASS fallback is degraded and is never presented as detailed delivery. Optional Tripo PBR texturing runs only when texturing.enabled and texturing.confirm_live are explicitly true; an API key means capability, never consent. The procedural package is always retained. The four legacy tools are experimental only.");
	api.registerMemoryLayer({ name: "elevation-3d-research", path: "memory/elevation-3d/README.md", description: "Geometry-locked architectural 3D research and decisions" });
	api.registerTool({ name: "elevation_3d_run", description: "Autonomously produce a complete candidate package: enrich and validate one geometry-locked GLB, then generate and browser-verify eight presentation views. Optional explicitly approved Tripo PBR texturing preserves the authoritative MASS and procedural fallback.", inputSchema: { properties: { candidate_id: { type: "string" }, dataset_root: { type: "string" }, output_root: { type: "string" }, approved_image: { type: "string" }, run_id: { type: "string" }, texturing: { type: "object", properties: { enabled: { type: "boolean" }, confirm_live: { type: "boolean" }, reference_image: { type: "string" }, max_credits: { type: "integer" }, seed: { type: "integer" }, dry_run: { type: "boolean" } } } } }, handler: async (args, signal) => ({ text: JSON.stringify(redactSecrets(await runElevation3d({ candidateId: args.candidate_id ?? "creative-013", datasetRoot: args.dataset_root ?? datasetRoot, outputRoot: args.output_root ?? outputRoot, approvedImage: args.approved_image, runId: args.run_id, texturing: args.texturing ? { enabled: args.texturing.enabled === true, confirmLive: args.texturing.confirm_live === true, referenceImage: args.texturing.reference_image, maxCredits: args.texturing.max_credits, seed: args.texturing.seed, dryRun: args.texturing.dry_run === true } : undefined, signal })), null, 2) }) });
	api.registerTool({ name: "elevation_3d_facade_agent_run", description: "Run the geometry-locked facade comparison through the approved bounded harness. Defaults to dry-run preflight and requires explicit live confirmation plus provider cost ceilings for paid stages.", inputSchema: facadeAgentToolSchema(), handler: async (args, signal) => ({ text: JSON.stringify(redactSecrets(await runFacadeAgentTool(args, signal, { datasetRoot, outputRoot }, api.facadeAgentDependencyFactory, facadeFetch)), null, 2) }) });
	api.registerTool({ name: "elevation_3d_facade_design_agent", description: "Opt-in LLM facade design workflow. The model proposes typed architectural intent while deterministic code owns coordinates, GLB compilation, technical elevations, perspective rendering, validation, and crash-safe promotion.", inputSchema: facadeDesignAgentToolSchema(), handler: async (args, signal) => ({ text: JSON.stringify(redactSecrets(await runFacadeDesignAgentTool(args, signal, { datasetRoot, outputRoot }, api.facadeDesignDependencyFactory)), null, 2) }) });
	api.registerTool({ name: "elevation_3d_prepare", description: "Experimental legacy tool: verify an immutable MASS candidate and prepare a two-provider generation plan without external API calls.", inputSchema: { properties: { dataset_root: { type: "string" }, candidate_id: { type: "string" }, facade_brief: briefSchema, output_root: { type: "string" } }, required: ["facade_brief"] }, handler: async (args) => { const plan = await prepareRun({ datasetRoot: args.dataset_root ?? datasetRoot, candidateId: args.candidate_id ?? "creative-004", facadeBrief: args.facade_brief, outputRoot: args.output_root ?? outputRoot }); return { text: JSON.stringify({ plan_path: join(plan.run_dir, "plan.json"), run_dir: plan.run_dir, plan_id: plan.plan_id, approval_id: plan.approval_id, estimated_cost_cny: plan.estimated_cost_cny, candidate_id: plan.candidate_id, provider_calls: 2 }, null, 2) }; } });
	api.registerTool({ name: "elevation_3d_generate", description: "Experimental legacy tool: after explicit approval, submit exactly one Hunyuan and one Wan job for a prepared plan.", inputSchema: { properties: { plan_path: { type: "string" }, approval_id: { type: "string" }, confirm_live: { type: "boolean" }, approved_max_cost_cny: { type: "number" } }, required: ["plan_path", "approval_id", "confirm_live", "approved_max_cost_cny"] }, handler: async (args) => ({ text: JSON.stringify(await executeRun({ planPath: args.plan_path, approvalId: args.approval_id, confirmLive: args.confirm_live, approvedMaxCostCny: args.approved_max_cost_cny }), null, 2) }) });
	api.registerTool({ name: "elevation_3d_resume", description: "Experimental legacy tool: poll stored provider jobs without creating new paid jobs.", inputSchema: { properties: { run_dir: { type: "string" }, wait: { type: "boolean" } }, required: ["run_dir"] }, handler: async (args) => ({ text: JSON.stringify(await resumeRun({ runDir: args.run_dir, wait: args.wait ?? false }), null, 2) }) });
	api.registerTool({ name: "elevation_3d_preview", description: "Experimental legacy tool: serve a completed or partial run as a local static web preview.", inputSchema: { properties: { run_dir: { type: "string" }, port: { type: "integer" } }, required: ["run_dir"] }, handler: async (args) => ({ text: await startPreview(args.run_dir, args.port ?? api.config.preview_port ?? 4173) }) });
}
